# Generated by Django 5.1.4 on 2025-05-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# users.migrations.0011_populate_initial_data



def create_categories(apps, schema_editor):
    Category = apps.get_model("users", "Category")
    categories = [
        "Celular",
        "Fone de ouvido",
        "Carregador",
        "Notebook",
        "Case Notebook",
        "Case Fone",
        "Tablet",
        "Mouse",
        "Smartwatch",
        "Suporte Notebook",
        "Carregador Portátil",
        "Casaco",
        "Blusa",
        "Camiseta",
        "Brinco",
        "Anel",
        "Óculos",
        "Relógio",
        "Piercing",
        "Boné",
        "Chapéu",
        "Mochila",
        "Carteira",
        "Touca",
        "Chinelo",
        "Colar",
        "Pulseira",
        "Pingente",
        "Presilha de Cabelo",
        "Batom",
        "Gloss",
        "Sombra",
        "Base",
        "Lápis de olho",
        "Blush",
        "Livro",
        "Apostila",
        "Caderno",
        "Lápis",
        "Borracha",
        "Caneta",
        "Lapizeira",
        "Anotações",
        "Grampeador",
        "Estojo",
        "Calculadora",
        "Calculadora Científica",
        "Planner",
        "Stylus",
        "Guarda-chuva",
        "Garrafa de Água",
        "Carteira de Identidade",
        "Carteira de Motorista",
        "Passe Estudantil",
        "Passe de Ônibus",
        "Cartão SUS",
        "Chaves",
        "Nessesair",
        "Outra",
    ]

    # Organize categorias em ordem alfabética, mantendo "Outra" ou "Outro" no final
    categories = sorted(categories)
    categories.remove("Outra")  # Remove "Outra" para adicionar no final
    categories.append("Outra")  # Adiciona "Outra" no final

    for idx, category in enumerate(categories, start=1):
        category_id = "00" if category.lower() in ["outra"] else f"{idx:02d}"
        Category.objects.get_or_create(
            name=category, category_id=category_id
        )  # A ID é '00' para 'Outra'


def create_locations(apps, schema_editor):
    Location = apps.get_model("users", "Location")
    locations = [
        "UAC",
        "Bebedouros - UAC",
        "Biblioteca - UAC",
        "Mesas de Estudos - UAC",
        "Mesas de Dama - UAC",
        "Mesas O Belisco - UAC",
        "Mesanino - UAC",
        "Anfiteatro - UAC",
        "Banheiros - UAC",
        "Estacionamento - UAC",
        "Jardim - UAC",
        "I1 - UAC",
        "I2 - UAC",
        "I3 - UAC",
        "I4 - UAC",
        "I5 - UAC",
        "I6 - UAC",
        "I7 - UAC",
        "I8 - UAC",
        "I9 - UAC",
        "I10 - UAC",
        "S1 - UAC",
        "S2 - UAC",
        "S3 - UAC",
        "S4 - UAC",
        "S5 - UAC",
        "S6 - UAC",
        "S7 - UAC",
        "S8 - UAC",
        "S9 - UAC",
        "S10 - UAC",
        "UED",
        "Bebedouros - UED",
        "Mesa de estudos - UED",
        "Mesanino - UED",
        "Mocap - UED",
        "Banheiros - UED",
        "Mesas Redondas - UED",
        "Sala de Professor - UED",
        "Estacionamento - UED",
        "Laboratórios - UED",
        "LDTEA",
        "Banheiros - LDTEA",
        "Estacionamento - LDTEA",
        "Laboratórios - LDTEA",
        "RU",
        "Banheiros - RU",
        "Mesas - RU",
        "Restaurante - RU",
        "Caixa - RU",
        "Box - RU",
        "Jardim - RU",
        "Diretório Acadêmico - DA",
        "Quadra Poliesportiva",
        "Monumento lado ru",
        "Guarita Estacionamento Sul",
        "Guarita Estacionamento Norte",
        "Outro",
    ]

    # Organize locais em ordem alfabética, mantendo "Outro" no final
    locations = sorted(locations)
    locations.remove("Outro")  # Remove "Outro" para adicionar no final
    locations.append("Outro")  # Adiciona "Outro" no final

    for idx, location in enumerate(locations, start=1):
        location_id = "00" if location.lower() in ["outro"] else f"{idx:02d}"
        Location.objects.get_or_create(
            name=location, location_id=location_id
        )  # A ID é '00' para 'Outro'


def create_colors(apps, schema_editor):
    Color = apps.get_model("users", "Color")
    colors = [
        "Amarelo",
        "Laranja",
        "Verde",
        "Vermelho",
        "Azul",
        "Rosa",
        "Preto",
        "Branco",
        "Marrom",
        "Bege",
        "Cinza",
        "Prata",
        "Dourado",
        "Bronze",
        "Estampado",
        "Outra",
    ]

    # Organize cores em ordem alfabética, mantendo "Outra" no final
    colors = sorted(colors)
    colors.remove("Outra")  # Remove "Outra" para adicionar no final
    colors.append("Outra")  # Adiciona "Outra" no final

    for idx, color in enumerate(colors, start=1):
        color_id = "00" if color.lower() in ["outra"] else f"{idx:02d}"
        Color.objects.get_or_create(name=color, color_id=color_id)  # A ID é '00' para 'Outra'


def create_brands(apps, schema_editor):
    Brand = apps.get_model("users", "Brand")
    brands = [
        "Dell",
        "Asus",
        "Vaio",
        "Sony",
        "Samsung",
        "LG",
        "Lenovo",
        "Apple",
        "Acer",
        "Xiaomi",
        "Huawei",
        "Motorola",
        "JBL",
        "HP",
        "Toshiba",
        "Razer",
        "Kingston",
        "SanDisk",
        "Nokia",
        "Tapaware",
        "Stanley",
        "Bic",
        "Adidas",
        "Nike",
        "New Balance",
        "Puma",
        "Oaklay",
        "Vans",
        "Hay-Ban",
        "Havaianas",
        "Levi's",
        "RRDD",
        "UnB",
        "FGA",
        "FCTE",
        "Avon",
        "O Boticário",
        "Dior",
        "Outra",
    ]

    # Organize marcas em ordem alfabética, mantendo "Outra" no final
    brands = sorted(brands)
    brands.remove("Outra")  # Remove "Outra" para adicionar no final
    brands.append("Outra")  # Adiciona "Outra" no final

    for idx, brand in enumerate(brands, start=1):
        brand_id = "00" if brand.lower() in ["outra"] else f"{idx:02d}"
        Brand.objects.get_or_create(name=brand, brand_id=brand_id)  # A ID é '00' para 'Outra'




class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_category_remove_item_image_item_color_and_more'), ('users', '0003_userprofile'), ('users', '0003_brand_color_alter_item_description_item_brand_and_more'), ('users', '0004_merge_20241229_1953'), ('users', '0005_location_alter_item_location'), ('users', '0006_remove_item_is_valuable'), ('users', '0007_item_barcode'), ('users', '0008_alter_item_category_alter_item_location'), ('users', '0009_item_matches_alter_item_status'), ('users', '0010_item_matches_alter_item_status'), ('users', '0011_populate_initial_data')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category_id', models.CharField(max_length=10, unique=True)),
            ],
        ),


        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category')),
                ('location', models.CharField(max_length=100)),
                ('is_valuable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('color', models.CharField(blank=True, choices=[('Red', 'Vermelho'), ('Blue', 'Azul'), ('Green', 'Verde'), ('Black', 'Preto'), ('White', 'Branco'), ('Other', 'Outro')], max_length=10)),
                ('found_lost_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('found', 'Achado'), ('lost', 'Perdido')], default='lost', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.item')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('brand_id', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_id', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.color'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location_id', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_valuable',
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('welcome_email_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matched_with', to='users.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('lost', 'Lost')], default='lost', max_length=10),
        ),
        migrations.RunPython(create_categories),
        migrations.RunPython(create_locations),
        migrations.RunPython(create_colors),
        migrations.RunPython(create_brands),
    ]
