# Generated by Django 5.1.4 on 2024-12-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_chat_chatroom_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='item_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
