# Generated by Django 5.1.4 on 2025-05-26 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_chatroom_item_description_chatroom_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.ManyToManyField(
                blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
