# Generated by Django 5.1.4 on 2026-04-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_chatroom_item_description_chatroom_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
